### PR TITLE
Refactor CLI setup script, add prompts for muting and skipping native youtube ads

### PR DESCRIPTION
**Pull request by ryankupk**
RE: #149 - the CLI setup wizard only sets the `skip_ads` and `mute_ads` config options to false and does not give any option to set them to true during the setup process. This change adds some minor refactorings for some things in the script like using a bespoke function for prompting the user for y/n, as well as adds prompts for skipping/muting native ads and saves the choice to the config.

### CODE REVIEW

**Comment by dmunozv04** [comment]
Thanks for the contribution to bring feature parity between both config editors! I'll make sure to review it when I have time

**Comment by ryankupk** [comment]
Thanks @dmunozv04. I'm not married to any line here, and I know that pulling the strings out to constants can be controversial. I'm open to any feedback. 

I also saw that github is reporting every line as different but locally the git diff is a lot cleaner. I'm not sure if maybe it's a linefeed thing, I don't think that it's tab width or anything like that. I can look deeper if you're concerned about that at all.

**Comment by dmunozv04** [comment]
It does look cleaner this way. I merged new changes into the branch

**Comment by dmunozv04** [comment]
@ryankupk merged!

**Pull request merged**
