### PR TITLE
Implement autoplay on/off toggle

### PR DESCRIPTION
**Pull request by Ravioli8235**
I have been test-driving this for at least a few weeks now on two LG tvs, works pretty well, didn't have an issue so far. If autoplay is set to false, it exits to the main screen.

https://github.com/dmunozv04/iSponsorBlockTV/issues/82

### CODE REVIEW

**Comment by dmunozv04** [comment]
I’d like to test autoplay being set on, since without the explicit flag it took some weeks to break. I’ll run it myself for a couple of weeks and let you know

**Comment by Ravioli8235** [comment]
Sure thing, let me know how it goes.

**Comment by dmunozv04** [comment]
@infowolfe feel free to try this image: ghcr.io/dmunozv04/isponsorblocktv:pr-161 
It's based on this PR. If all goes well, this will be merged soon.

**Comment by infowolfe** [comment]
> @infowolfe feel free to try this image: ghcr.io/dmunozv04/isponsorblocktv:pr-161 It's based on this PR. If all goes well, this will be merged soon.

Appreciate it, I'll test and report back.

**Comment by dmunozv04** [comment]
@Ravioli8235 I've been testing this for a while on my devices and I have to say that it works wonderfully. Thanks for your work!
The only issue I see is the panel in the tui configurator seems to try to fill the screen and not just fit around the checkbox and the description.

**Comment by Ravioli8235** [comment]
Thanks, I missed that somehow, should be good now, please check it.

**Comment by dmunozv04** [comment]
@Ravioli8235 I changed it in the tcss file to add bottom padding, thanks!

**Comment by dmunozv04** [comment]
@Ravioli8235 merged!

**Pull request merged**
