### PR TITLE
Add Google TV status to README

### PR DESCRIPTION
**Pull request by JoshCooley**
I tested this on the Chromecast with Google TV.

The CCwGTV is quite different from older Chromecasts. It runs on a branded version of Android TV. So we could mark compatibility w/ Android TV. I'm like 90% sure it would work, but I don't actually have something with a branded "Android TV" OS so I can't be sure

Initially I was going to mark Chromecast as compatible, but I'm getting some errors on my older Chromecast 4K (which does not use Android TV). I'll open an issue for that (or a PR if I can figure it out).

Note that there is an older platform called "Google TV" that is unrelated. It was retired 10 years ago, but could cause confusion. Could use the phrase "Chromecast with Google TV" but I didn't want to make the table wider. The initialism `CCwGTV` is pretty well known, so could use that instead.

### CODE REVIEW

**Comment by dmunozv04** [comment]
Google TV device names are a bit confusing. Thanks for testing it on the CCwGTV, and for trying to find what’s wrong on your Chromecast 4K. The help is definitely appreciated since I don’t currently have a chromecast to test on

**Comment by dkmonaghan** [comment]
If it helps, I've just tested on my CCwGTV 4K and an NVIDIA Shield 2019 (Shield 8.2.3, Android 9), both worked great with no issues.

**Comment by cgriffith99** [comment]
I have multiple Onn (Wal-Mart brand) Android TV devices from 2 or 3 years ago. I know they recently went to Google TV with their new one this year, but I still have the Android TV devices/firmware. I will test today and let everyone know if it works for sure.

**Comment by dmunozv04** [comment]
Thanks for the info guys!

**Comment by cgriffith99** [comment]
I'm testing now and it doesn't seem to be working, but I'm not quite sure if I have everything set up correctly. 

I am running your app on my PC, have linked with a code (your app shows a device screen id for the Android TV device) and have gotten a YouTube Data API v3 key to associate. Is this correct? I couldn't find any step by steps for making sure I config this correctly

I tried a SponsorBlock video id that is in their database and it is still playing sponsored ads at the beginning, etc.

**Comment by dmunozv04** [comment]
> I'm testing on an Onn Android TV device and it doesn't seem to be working, but I'm not quite sure if I have everything set up correctly.
> 
> I am running your app on my PC, have linked with a code (your app shows a device screen id for the Android TV device) and have gotten a YouTube Data API v3 key to associate. Is this correct? I couldn't find any step by steps for making sure I config this correctly
> 
> I tried a SponsorBlock video id that is in their database and it is still playing sponsored ads at the beginning, etc.

Would you mind opening a separate issue so I can look into this in greater detail?

**Pull request merged**
